name: Publish Packages and Create Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Cache PNPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Build packages
        run: pnpm -r run build

      - name: Run version bump
        run: pnpm changeset version

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: false
          branch: main
          commit: "chore(release): update versions to ${{ env.VERSION }} [skip ci]"
          title: "Release PR: exirdjs@v${{ env.VERSION }}"

      - name: Generate changelog
        id: changesets
        uses: changesets/action@v1
        with:
          publish: false

      - name: Extract version number
        id: get_version
        run: echo "VERSION=$(jq -r '.version' packages/exird/package.json)" >> $GITHUB_ENV

      - name: Publish Packages
        run: pnpm changeset publish

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: exirdjs@v${{ env.VERSION }}
          body: |
            Changes in this release:
            ${{ steps.changesets.outputs.changelog }}
          draft: false
          prerelease: false
