name: Publish Packages and Create Release

on:
  push:
    branches-ignore: 
    - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Cache PNPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Build packages
        run: pnpm -r run build

      - name: Generate changelog and version packages
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: release packages"
          publish: false

      - name: Push tags
        run: git push --set-upstream origin changeset-release/dev --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Extract version number
        id: get_version
        run: echo "VERSION=$(jq -r '.version' packages/exird/package.json)" >> $GITHUB_ENV

      # - name: Create GitHub Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: "v${{ env.VERSION }}"
      #     release_name: "Release v${{ env.VERSION }}"
      #     body: |
      #       Changes in this release:
      #       ${{ steps.changesets.outputs.changelog }}
      #     draft: false
      #     prerelease: false
