name: Publish Packages and Create Release

on:
  push:
    branches-ignore: 
    - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Cache PNPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Build packages
        run: pnpm -r run build

      - name: Generate changelog and version packages
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: release packages"
          publish: false

      - name: Extract version number
        id: get_version
        run: echo "VERSION=$(jq -r '.version' packages/exird/package.json)" >> $GITHUB_ENV
      
      # - name: Publish Packages # I will not publish immediately
      #   run: pnpm changeset publish

      - name: Get Pull Request Body
        id: get_pr_body
        run: |
          PR_URL=$(gh pr list --repo ${{ github.repository }} --state open --author github-actions[bot] --json url --jq '.[0].url')
          PR_BODY=$(gh pr view $PR_URL --json body --jq '.body')
          echo "PR_BODY<<EOF" >> $GITHUB_ENV
          echo "$PR_BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "@exirdjs/v${{ env.VERSION }}"
          release_name: "Releases v${{ env.VERSION }}"
          body: |
            Changes in this release:
            ${{ env.PR_BODY }}
          draft: false
          prerelease: false
